### ISSUE TITLE
Revision branch to-do's

### ISSUE THREAD

**Issue by lokka30** [lokka30/OnlineRecord#8]
To-do's for the revision branch:

- [x]     - test revision works
- [x]     - add data in migration
- [ ]     - test data migration works
-  - ~~clean up commands code~~ cancelled; see #9 
- [ ]     - test commands work
- [ ] #2 
- [ ] #3 
- [ ] #4 
- [x]     - clean up README
- [ ]     - push update :)
